### ISSUE TITLE
Updated to 1.5: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#10]
![screen shot 2015-04-15 at 6 47 04 pm](https://cloud.githubusercontent.com/assets/4752289/7170873/e52fa2f2-e39f-11e4-8813-0f30a3351325.png)

**Comment by EricMCSE76** [comment]
Same here.... never ran into that with other releases.  Odd.

**Comment by EricMCSE76** [comment]
Instead of unzipping over top of the existing files - I wiped out the directory (left the WinkAtHome folder - just deleted contents), unzipped again and recycled the app pool in iis.  Came up fine after that.

**Comment by EricMCSE76** [comment]
Well - everything except the monitor page anyway :)

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index 

ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index]
   Wink.winkGetRobots() +1981
   WinkAtHome.Controls.Robots.BindData() +285
   WinkAtHome.Controls.Robots.Page_Load(Object sender, EventArgs e) +535
   System.Web.UI.Control.OnLoad(EventArgs e) +94
   System.Web.UI.Control.LoadRecursive() +154
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4808

**Comment by trunzoc** [comment]
I'm on it.

**Comment by trunzoc** [comment]
in Settings, is "Hide-Empty-Robots" set to true or false?

**Comment by EricMCSE76** [comment]
I didn't even see that. That'll teach me for not looking there first.  It's false for both... I changed to true, saved, went to monitor and got same.

[ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index]
   Wink.winkGetRobots() +1981
   WinkAtHome.Controls.Robots.BindData() +134
   WinkAtHome.Controls.Robots.Page_Load(Object sender, EventArgs e) +535
   System.Web.UI.Control.OnLoad(EventArgs e) +94
   System.Web.UI.Control.LoadRecursive() +154
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Control.LoadRecursive() +251
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +4808

**Comment by ghost** [comment]
False on mine and monitor page does not work

**Comment by EricMCSE76** [comment]
David - the unzip to a clean directory fixed your initial issue too?

**Comment by ghost** [comment]
Yes

**Comment by EricMCSE76** [comment]
Just grabbed the 1.5.1... same issue :(

**Comment by trunzoc** [comment]
yup.  That was just the menu thing.  Working on this now

**Comment by trunzoc** [comment]
I just reupped a new file to v1.5.1.

Can you please grab it and unzip?

The Robot issue will most likely still be there, but I added a new button to the settings menu called "Get Raw Robot Data"

Please click that and email the text to me.  I need to see what you guys have in the robots that's killing it on your side, but not on mine.

**Comment by ghost** [comment]
emailed

**Comment by EricMCSE76** [comment]
I'll grab that info from mine now

**Comment by trunzoc** [comment]
Release v1.5.2 

https://github.com/trunzoc/WinkAtHome/releases/tag/v1.5.2

**Comment by ghost** [comment]
Working here now!

**Comment by ghost** [comment]
What was wrong?

**Comment by trunzoc** [comment]
I found out earlier today that Schedules form inside the light window show up as robots.  I never used them, barely knew they existed.  I made some changes to the robots code to populate a "next schedule run" attribute.
my null checking was indepth enough.  some robots are missing the JSON field that populates it.

I think they are location robots.

is your "Arrives Home" robot location based?

**Comment by ghost** [comment]
Yes it is location based, but the location feature is crap so it is disabled.  The damn thing kept thinking I was coming and going while my phone was laying on my nightstand.

-- 
David Gruhin
Sent with Airmail

On April 15, 2015 at 9:50:56 PM, trunzoc (notifications@github.com) wrote:

I found out earlier today that Schedules form inside the light window show up as robots. I never used them, barely knew they existed. I made some changes to the robots code to populate a "next schedule run" attribute.
my null checking was indepth enough. some robots are missing the JSON field that populates it.

I think they are location robots.

is your "Arrives Home" robot location based?
