### ISSUE TITLE
Broken Page Layout since 1.5

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#11]
![screen shot 2015-04-15 at 7 31 06 pm](https://cloud.githubusercontent.com/assets/4752289/7171418/089fd972-e3a6-11e4-9b2e-e0c08fc6ded9.png)

Width:40px is causing a problem

**Comment by ghost** [comment]
When collapsed adding:

  width: 40px;
  height: 100%;
  display: inline-table;

to the ctl00_cellMenu 

gets you:

![screen shot 2015-04-15 at 7 34 34 pm](https://cloud.githubusercontent.com/assets/4752289/7171440/7b7f4568-e3a6-11e4-9539-2c84c0fdc20a.png)

**Comment by ghost** [comment]
Just add 

  height: 100%;
  display: inline-table;

to expanded and collapsed state and it fixes it (at least in Chrome)

**Comment by trunzoc** [comment]
suppsed to look like this...
![image](https://cloud.githubusercontent.com/assets/3355868/7171516/6e07d7d2-e3a7-11e4-8af8-cd9c8d31bb2d.png)

**Comment by ghost** [comment]
Perhaps in IE... it does not in Chrome or Firefox
![screen shot 2015-04-15 at 7 50 13 pm](https://cloud.githubusercontent.com/assets/4752289/7171610/aadfd1f4-e3a8-11e4-8dd3-77239cca703e.png)

**Comment by ghost** [comment]
only thing I can come up with that seems cross browser on collapse is to add:

  -ms-transform: rotate(90deg);
  -webkit-transform: rotate(90deg);
  transform: rotate(90deg);
  height: 100%;
  padding-top: 60px;
  padding-bottom: 60px;

I do not love what that does...

Can I make a plea for Bootstrap integration, replacing tables with Divs and external stylesheet for CSS so I can contribute?

**Comment by trunzoc** [comment]
Got it  I'll clean it up some now that it's in the right direction...

![image](https://cloud.githubusercontent.com/assets/3355868/7171764/f6a7ef5c-e3aa-11e4-9647-fdee11ab8faf.png)

**Comment by trunzoc** [comment]
I never used bootstrap :(  One of those things where I don't mind learning, but it has to wait.

**Comment by ghost** [comment]
Totally understood.

It is really easy and very flexible.

Sent from my iPhone

On Apr 15, 2015, at 8:13 PM, trunzoc notifications@github.com wrote:

I never used bootstrap :( One of those things where I don't mind learning,
but it has to wait.

**Comment by trunzoc** [comment]
done.  Let me find out what is wrong with the robots now.
![image](https://cloud.githubusercontent.com/assets/3355868/7171951/b4cd2c16-e3ad-11e4-912e-96004b7ab911.png)
