### ISSUE TITLE
Feature Request: Have Settings.aspx show version #

### ISSUE THREAD

**Issue by 4rsfed** [trunzoc/WinkAtHome#13]
With all the upgrades/improvements going on, it's difficult to know which version we are on unless we remember. Would be nice to have something in the Settings page that we can track back to GitHub to make sure we're on the correct/newest build.

(another way to think of it, to verify the upgrade has been successful, unzipping over the WinkAtHome folder...)

**Comment by trunzoc** [comment]
Like so,,,?

![image](https://cloud.githubusercontent.com/assets/3355868/7193191/3b5106e6-e46b-11e4-87bc-97bd59deb000.png)

**Comment by 4rsfed** [comment]
exactly thanks!
