### ISSUE TITLE
I think deleted robots are showing up

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#15]
I think deleted robots are showing up...??

Scheduled event and trigger I do not see those on my Wink App.

![screen shot 2015-04-19 at 10 19 48 pm](https://cloud.githubusercontent.com/assets/4752289/7222746/382c5622-e6e2-11e4-8a5b-f2141f45c816.png)

**Comment by ghost** [comment]
No they are Power Strip Items:

Schedule Event:
{
  "robot_id": "553294",
  "name": "Scheduled Event",
  "enabled": true,
  "creating_actor_type": "powerstrip",
  "creating_actor_id": "14934",
  "automation_mode": "legacy_scheduled_outlet_state",
  "fired_limit": 0,
  "last_fired": null,
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "7dc3df7d03a2a84e3ff3d95d84d3253877cbd8ef"
    }
  },
  "effects": [],
  "causes": [],
  "restrictions": []
}

Trigger:

{
  "robot_id": "659578",
  "name": "Trigger",
  "enabled": true,
  "creating_actor_type": "powerstrip",
  "creating_actor_id": "15341",
  "automation_mode": "legacy_trigger",
  "fired_limit": 0,
  "last_fired": null,
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "c136c51a09bbe000bb1ab27fb76b7b086ffeb518"
    }
  },
  "effects": [],
  "causes": [],
  "restrictions": []
}

**Comment by trunzoc** [comment]
Go into settings and change "Hide-Empty-Robots" to "true" (no quotes).

If that setting does not already exist, click the "Manually Edit Settings" button and paste ',"Hide-Empty-Robots":"true"' in right after the "WinkClientSecret" entry
