### ISSUE TITLE
FEATURE REQUEST - Paired Device Inventory

### ISSUE THREAD

**Issue by EricMCSE76** [trunzoc/WinkAtHome#17]
Suggesting the addition of an inventory of paired devices accessible from any "hub" device (Wink Hub, Link Hub, Wink Relay).  The inventory could simply display a list of device name and type - grouped by type, ordered by name.  I'm thinking clicking on the device could display this information - similar to clicking on the Wink Hub in the app where it shows how many of each device.  It would pop up an info box that provides the inventory information.

**Comment by trunzoc** [comment]
https://github.com/trunzoc/WinkAtHome/releases/tag/v1.5.5597.23167
