### ISSUE TITLE
Feature request Multi sign in 

### ISSUE THREAD

**Issue by TDWhbp** [trunzoc/WinkAtHome#18]
Is there a way to make this so more than one Wink user can sign to wink at home I.e kids / mom/ dad? not all at the same time but I would love to use this for a command center.

**Comment by trunzoc** [comment]
Do they all have their own Wink accounts, or would the requested sign-in just be for the webpage and they would all be using devices from a single Wink account?

**Comment by TDWhbp** [comment]
Each would have their own wink account.

**Comment by trunzoc** [comment]
https://github.com/trunzoc/WinkAtHome/releases/tag/v1.5.5602.27402
