### ISSUE TITLE
Misc Bugs / Corrections

### ISSUE THREAD

**Issue by EricMCSE76** [trunzoc/WinkAtHome#19]
1 ) On device info screen - button is now Save and Close.  If I don't choose to use device ordering and leave it blank - I can't close out of the info screen unless I enter a value.
2 ) On info for robots, shortcuts and groups - the button just is labeled as close.  Clicking on it does nothing.  I don't get the warning that I need to have a value in the position box. If I put a value in the position box and click the close button - still does nothing.  If I put a value in the position box and hit enter - the box closes.

3 ) Ascend Garage Door - For some reason it has a battery property which is null.  App interprets this as battery 0%.  There isn't a battery in Ascend so - If Model = Ascend --- ignore battery property.
   "battery": null,
    "battery_updated_at": null,

4 ) Ascend Garage Door - Consider adding a red ! when door is open - similar to trippers

**Comment by trunzoc** [comment]
done
done
done

and done
