### ISSUE TITLE
Need ability to Monitor Hub status and reboot if needed

### ISSUE THREAD

**Issue by batrad** [trunzoc/WinkAtHome#2]
this is more of a request, than an issue with the code (more of an issue with the Hub)

You can monitor the status of the Wink Hub my connecting locally to 

WinkHubIP:80. We could have a timer such that if over 5 (or another number of your choosing) 1 minute polls, you dont get a response from the Hub, reboot the device.

if the Hub it down, it would be helpful to reboot the device using a non ZWave/Zigbee device like WeMo
WeMo Api http://search.cpan.org/~ericblue/WebService-Belkin-WeMo-1.0/

thanks

**Comment by trunzoc** [comment]
After much time sent playing with the API and getting in-depth examples, this will just not be possible from within the app.  The API does not accurately report if a device is connected or not.  I have a switch that has been disconnected for over a week and the API still says "Connection: true" for it.

During "The WInkening", my hub was down for 3 days and not once did the API tell me it wasn't connected.

My suggestion would be to use a program like "Tasker" for android to ping your hub's IP on a regular basis to alert you if it is ever unreachable.
