### ISSUE TITLE
controllable devices disappearing

### ISSUE THREAD

**Issue by TDWhbp** [trunzoc/WinkAtHome#20]
In upgrading some of my controllable devices disappeared... upon restart the only one left was my lock. The all still show up when viewing the group (lights) but not under the controllable devices tab.

**Comment by trunzoc** [comment]
This is an issue with the wink API.  They are working to fix it.

**Comment by TDWhbp** [comment]
Thanks for that info I thought I was loosing my mind.

**Comment by trunzoc** [comment]
I pushed up a release that uses a temp fix to get this stuff working while we wait for Wink to fix the API.
