### ISSUE TITLE
Control for Thermostat

### ISSUE THREAD

**Issue by EricMCSE76** [trunzoc/WinkAtHome#21]
Not sure if you wanted to do a temporary fix for the thermostats.  Here is the JSON from my Nest.

{
  "thermostat_id": "23421",
  "name": "Home Dining Room Thermostat",
  "locale": "en_us",
  "units": {
    "temperature": "f"
  },
  "created_at": 1419086572,
  "hidden_at": null,
  "capabilities": {},
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "cd58d71aba1963512fade1e386d7bc534d3f8bb7|thermostat-23421|user-145398"
    }
  },
  "user_ids": [
    "145398"
  ],
  "triggers": [],
  "desired_state": {},
  "manufacturer_device_model": "nest",
  "manufacturer_device_id": "Wyc73fGVax7Ya-R4ovP-SExx11Qobba_",
  "device_manufacturer": "nest",
  "model_name": "Learning Thermostat",
  "upc_id": "168",
  "hub_id": null,
  "local_id": null,
  "radio_type": null,
  "linked_service_id": "50847",
  "last_reading": {
    "connection": true,
    "connection_updated_at": 1431049157.7519262,
    "powered": false,
    "powered_updated_at": 1431049157.7519777,
    "min_set_point": 20.0,
    "min_set_point_updated_at": 1431049157.7519991,
    "max_set_point": 23.888888888888889,
    "max_set_point_updated_at": 1431049157.7520068,
    "mode": "heat_only",
    "mode_updated_at": 1430946942.8452034,
    "users_away": false,
    "users_away_updated_at": 1431049157.7520278,
    "fan_timer_active": false,
    "fan_timer_active_updated_at": 1431049157.751992,
    "temperature": 23.0,
    "temperature_updated_at": 1431049157.751946,
    "external_temperature": null,
    "external_temperature_updated_at": null,
    "deadband": 1.5,
    "deadband_updated_at": 1431049157.7519538,
    "min_min_set_point": null,
    "min_min_set_point_updated_at": null,
    "max_min_set_point": null,
    "max_min_set_point_updated_at": null,
    "min_max_set_point": null,
    "min_max_set_point_updated_at": null,
    "max_max_set_point": null,
    "max_max_set_point_updated_at": null,
    "modes_allowed": [
      "auto",
      "heat_only",
      "cool_only"
    ],
    "modes_allowed_updated_at": 1431049157.7520137,
    "units": "f",
    "units_updated_at": 1431049157.7519379,
    "eco_target": true,
    "eco_target_updated_at": 1431049157.7519617,
    "manufacturer_structure_id": "SCtOxJ3-MWw0glF8ScNOgmUXXPVl8Q1mdYJaib0MYcl_ZP6uUaCVeQ",
    "manufacturer_structure_id_updated_at": 1431049157.7519703,
    "has_fan": true,
    "has_fan_updated_at": 1431049157.7519846,
    "fan_duration": 0,
    "fan_duration_updated_at": 1431049157.7520208,
    "last_error": null,
    "last_error_updated_at": 1421787062.2703428,
    "desired_powered_updated_at": 1431005484.4858487,
    "desired_min_set_point_updated_at": 1431005484.4858694,
    "desired_max_set_point_updated_at": 1431005484.485878,
    "desired_mode_updated_at": 1431005484.4858854,
    "desired_users_away_updated_at": 1431005484.485894,
    "desired_fan_timer_active_updated_at": 1431005484.4859018,
    "connection_changed_at": 1430794098.20695,
    "powered_changed_at": 1430950518.7269628,
    "min_set_point_changed_at": 1430950518.7269847,
    "max_set_point_changed_at": 1430757474.2571824,
    "mode_changed_at": 1430824468.6797764,
    "temperature_changed_at": 1431049157.751946,
    "eco_target_changed_at": 1430950520.1249938,
    "desired_powered_changed_at": 1431005484.4858487,
    "desired_min_set_point_changed_at": 1431005484.4858694,
    "desired_max_set_point_changed_at": 1431005484.485878,
    "desired_mode_changed_at": 1431005484.4858854,
    "desired_users_away_changed_at": 1431005484.485894,
    "desired_fan_timer_active_changed_at": 1431005484.4859018
  },
  "lat_lng": [
    null,
    null
  ],
  "location": "",
  "smart_schedule_enabled": false
}

**Comment by trunzoc** [comment]
The problem is that "Desired_States" section has no entries.  That is where it SHOULD be telling us what we can control.  Without that being populated, I'd have to guess at the correct working, which is a crapshoot at best :(  sorry.
