### ISSUE TITLE
recommendation for hosting

### ISSUE THREAD

**Issue by mrose17** [trunzoc/WinkAtHome#23]
hi. let's say i wanted to run this myself on a hosting service that supports windows: here are the two obvious questions:
1. are there any windows hosting services that you recommend?
2. what version of windows should i provision?

thanks!

/mtr

**Comment by trunzoc** [comment]
I have it running on a public server in a closed beta.  If you interested in testing it out, let me know and I'll provide a link for you.

As far as a suggestion, I've used GoDaddy for a while and never had any complaints, so went with them again for this.

**Comment by mrose17** [comment]
many thanks, but i really like to run these things myself though(!!) so which version/edition/etc. of windows are you using?

**Comment by trunzoc** [comment]
I run it on 8.1 64-bit
