### ISSUE TITLE
Suggested enchancement

### ISSUE THREAD

**Issue by tfatykhov** [trunzoc/WinkAtHome#26]
On Monitor page display actual state of sensors like motion detected or tripper is in opened state etc. instead of showing icons.

**Comment by EricMCSE76** [comment]
I'm not sure I understand this. I personally like it the way it is. The icon itself behaves just as it does on the application with open or closed icons. Craig added a red exclamation marker to devices that are open. Not sure what else anyone would need?

**Comment by trunzoc** [comment]
with the push to the public site, I changed a lot of stuff and neglected the indepth detail of the site.  I'll go through and make sure that sensors are displaying as they should.

Assuming everything is in working order, I'm going to leave the sensor tab as is.  The icons should be showing tripped and non-tripped versions as well as an exclamation mark when tripped.  If that's not the case, I will fix that.

**Comment by tfatykhov** [comment]
Sensor icons do not change at least for motion sensors. I have to click on the ... to check what is actual state of the sensor. Also, since it is a monitoring page spotter for example has several parameters like temperature, light. Same is for Wink Relay as well. so it would be better to actually see values on that monitor page. Nest also has temp and humidity. Again just a thought otherwise I do not see any difference between device by types - sensor pods page and monitor page. Similar to what wink app page has for that
![screenshot_2015-05-15-16-24-39](https://cloud.githubusercontent.com/assets/12263545/7661283/35c43da4-fb1f-11e4-93d0-8999475f1193.png)

**Comment by EricMCSE76** [comment]
Some of what he's able to provide is based on what's presented by the API.  I have Relay - I sent Craig over the data from relay and temp and humidity are not exposed via the API.  I also have Nest Thermostat... the API exposes the temp but does not expose humidity.    If you look at the JSON section on the device - you can see all of the available parameters and values that it sends over.  Wink recently "broke" the API and stopped sending over some things in the way they were previously...go figure.

**Comment by tfatykhov** [comment]
I understand that api is broken but we all hope they will fix it :)

**Comment by EricMCSE76** [comment]
Agreed.. btw here are my sensors (trippers) showing the appropriate status

![capture](https://cloud.githubusercontent.com/assets/11870446/7663687/d6adcfec-fb3c-11e4-95ac-e9c363fd3a5c.JPG)

**Comment by tfatykhov** [comment]
yes we identified that it is not the case for ecolink motion sensors

**Comment by trunzoc** [comment]
Timur, OK to close this now?

**Comment by tfatykhov** [comment]
up to you. It is not an issue more like a suggestion for future release. I just could not find more appropriate place :)
