### ISSUE TITLE
Sensor Status

### ISSUE THREAD

**Issue by rochoje** [trunzoc/WinkAtHome#3]
It would be great if the Sensor State could be shown.   I currently use the Window / Door sensors http://www.wink.com/products/quirkyge-tripper-windowithdoor-sensor/

to monitor my office and server room doors.   It would be great to be able to see if they are open / closed right from the site.

**Comment by trunzoc** [comment]
I've begun laying the groundwork for sensor implementation.  I have a couple motion sensors and door/window sensors on the way.  Once they arrive, I will get the sensors fully implemented.

**Comment by trunzoc** [comment]
Release 1.2.0 includes basic sensor display functionality.  Let me know what you think.

**Comment by rochoje** [comment]
Sorry, this ended up in spam for some reason.   I installed new version this morning and it looks good!  thanks

**Comment by trunzoc** [comment]
Great!
