### ISSUE TITLE
Behavior of Thermostat

### ISSUE THREAD

**Issue by EricMCSE76** [trunzoc/WinkAtHome#4]
The thermostat currently shows up as a house icon in the controllable devices.  Clicking the icon appears to turn off the furnace and clicking again turns the furnace back on and puts it in auto mode.  The interface doesn't indicate what the state is or what happens if it is clicked.  Attached capture of the interface and the result from the activity log

![capture](https://cloud.githubusercontent.com/assets/11870446/7066351/ae65fc9a-de8f-11e4-81ad-cceca21d8a77.JPG)
![img_5526](https://cloud.githubusercontent.com/assets/11870446/7066360/bdbbbe64-de8f-11e4-8213-c858b05ad9cf.PNG)

**Comment by trunzoc** [comment]
Thanks for the feedback Eric.

As of this writing, I have the images in place for thermostats and am working on the coding to make them work.  I have the new changes going into the "Thermostats" branch off the master.

If you are not opposed to downloading the source and compiling yourself, that will at least get the images and whatnot to look better.

I should have actual functionality in place by the end of the day today.

**Comment by EricMCSE76** [comment]
No problem.  Let me know when you have a compiled version to test and I'll play around with it a bit.  Looking forward to seeing how it looks.

**Comment by trunzoc** [comment]
Release 1.1.0 should fully enable most thermostats.
