### ISSUE TITLE
App crash when running shortcuts

### ISSUE THREAD

**Issue by EricMCSE76** [trunzoc/WinkAtHome#5]
Any time I run a shortcut, the app crashes with the following error.  The action works prior to the crash (ie the lights turn on / off / etc)  The app pool needs to be reset to get it back up and running.  The shortcuts are just turning Link lights on / off / adjusting brightness - not interfacing with any other devices.  The devices are able to be controlled individually without issue.

Input string was not in a correct format.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.FormatException: Input string was not in a correct format.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[FormatException: Input string was not in a correct format.]
   System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +11397397
   System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) +120
   System.Convert.ToInt32(String value) +49
   WinkAtHome.Controls.Devices.dlDevices_ItemDataBound(Object sender, DataListItemEventArgs e) +1347
   System.Web.UI.WebControls.DataList.OnItemDataBound(DataListItemEventArgs e) +115
   System.Web.UI.WebControls.DataList.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem) +151
   System.Web.UI.WebControls.DataList.CreateControlHierarchy(Boolean useDataSource) +644
   System.Web.UI.WebControls.BaseDataList.OnDataBinding(EventArgs e) +64
   System.Web.UI.WebControls.BaseDataList.DataBind() +80
   WinkAtHome.Controls.Devices.BindData() +286
   WinkAtHome.Controls.Devices.Page_Load(Object sender, EventArgs e) +481
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2841

**Comment by trunzoc** [comment]
Please test with the new release and let me know if this issue persists.

**Comment by EricMCSE76** [comment]
Just tested with new release - same behavior.  The lights turn on / turn off but the error is thrown and app pool has to be recycled to resume using the app.

[FormatException: Input string was not in a correct format.]
   System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal) +11397397
   System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info) +120
   System.Convert.ToInt32(String value) +49
   WinkAtHome.Controls.Devices.displayDevices(DataListItem item) +1914
   WinkAtHome.Controls.Devices.dlDevices_ItemDataBound(Object sender, DataListItemEventArgs e) +1954
   System.Web.UI.WebControls.DataList.OnItemDataBound(DataListItemEventArgs e) +115
   System.Web.UI.WebControls.DataList.CreateItem(Int32 itemIndex, ListItemType itemType, Boolean dataBind, Object dataItem) +151
   System.Web.UI.WebControls.DataList.CreateControlHierarchy(Boolean useDataSource) +643
   System.Web.UI.WebControls.BaseDataList.OnDataBinding(EventArgs e) +63
   System.Web.UI.WebControls.BaseDataList.DataBind() +80
   WinkAtHome.Controls.Devices.BindData() +680
   WinkAtHome.Controls.Devices.Page_Load(Object sender, EventArgs e) +921
   System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e) +85
   System.Web.UI.Control.OnLoad(EventArgs e) +79
   System.Web.UI.Control.LoadRecursive() +130
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Control.LoadRecursive() +200
   System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint) +2836

**Comment by EricMCSE76** [comment]
Looks like group control broke in this release.  Unable to turn groups on/off or adjust brightness of groups.  They are "clickable" but nothing happens (no errors, no response).  I tried this from the control page as well as the groups page itself.

**Comment by trunzoc** [comment]
I think the groups error is unrelated.  Is your phone app working for groups?  I am unable to control groups from the Official Wink App at this time. This leads me to believe that the issue is somewhere with Wink itself.  

I'll check this again tomorrow and see if anything has changed.

For the shortcut issue, is it all shortcuts, or only a few specific ones? if specific, please click the info "i" next to the shortcut icon and please send me the JSON string from one of the ones that fails.

if it's all, please just grab the JSON from any of them and send that over.

You can post it here, or email it to me at craig.trunzo@gmail.com if you don't want the info public.

**Comment by trunzoc** [comment]
The group thing actually seems weird.  I have 2 devices that absolutely will not get controlled by a group, but other devices work fine.  So not sure if there is some Wink-wide group issue ATM, or if something else is going on.  I'll keep an eye on it

**Comment by EricMCSE76** [comment]
Ref the groups - still not working today.  They work fine in the app itself (iPhone) and via the Relay.  If a light that is in the group is turned on - the status of the group changes as it should.  But - unable to click on the group to turn on or off nor change the brightness of a group.

Ref the shortcut issue... I wanted to take Windows 10 out of the picture so set it up on a Windows Server 2008 R2 VM... same issue there.  All shortcuts behave the same...in my case, they all adjust scenes of link lights - turn all off, turn all on full bright, living room dim, etc.  

Here is the -CORRECT- JSON from one of the shortcuts.

{
  "scene_id": "323370",
  "name": "Living Room Dim",
  "order": 0,
  "members": [
    {
      "object_type": "light_bulb",
      "object_id": "351553",
      "desired_state": {
        "brightness_updated_at": 1424559903.8736751,
        "external_power": null,
        "firmware_version": null,
        "update_needed_updated_at": null,
        "cost": null,
        "units_updated_at": null,
        "identify_mode_updated_at": null,
        "update_needed": null,
        "powered_updated_at": 1424559903.873662,
        "budget_velocity_updated_at": null,
        "updating_firmware_updated_at": null,
        "powering_mode": "dumb",
        "units": null,
        "budget_percentage": null,
        "firmware_version_updated_at": null,
        "identify_mode": null,
        "battery": null,
        "battery_updated_at": null,
        "color": null,
        "consumption_updated_at": null,
        "consumption": null,
        "updating_firmware": null,
        "schedule_enabled": null,
        "color_updated_at": null,
        "last_error": null,
        "powered": true,
        "connection": true,
        "powering_mode_updated_at": null,
        "budget_percentage_updated_at": null,
        "external_power_updated_at": null,
        "budget_velocity": null,
        "last_error_updated_at": null,
        "connection_updated_at": 1424559903.8736429,
        "schedule_enabled_updated_at": null,
        "cost_updated_at": null,
        "brightness": 0.02867925
      },
      "local_scene_id": null
    },
    {
      "object_type": "light_bulb",
      "object_id": "351564",
      "desired_state": {
        "brightness_updated_at": 1424560301.376138,
        "external_power": null,
        "firmware_version": null,
        "update_needed_updated_at": null,
        "cost": null,
        "units_updated_at": null,
        "identify_mode_updated_at": null,
        "update_needed": null,
        "powered_updated_at": 1424560301.376132,
        "budget_velocity_updated_at": null,
        "updating_firmware_updated_at": null,
        "powering_mode": "dumb",
        "units": null,
        "budget_percentage": null,
        "firmware_version_updated_at": null,
        "identify_mode": null,
        "battery": null,
        "battery_updated_at": null,
        "color": null,
        "consumption_updated_at": null,
        "consumption": null,
        "updating_firmware": null,
        "schedule_enabled": null,
        "color_updated_at": null,
        "last_error": null,
        "powered": false,
        "connection": true,
        "powering_mode_updated_at": null,
        "budget_percentage_updated_at": null,
        "external_power_updated_at": null,
        "budget_velocity": null,
        "last_error_updated_at": null,
        "connection_updated_at": 1424560301.376122,
        "schedule_enabled_updated_at": null,
        "cost_updated_at": null,
        "brightness": 0
      },
      "local_scene_id": null
    },
    {
      "object_type": "light_bulb",
      "object_id": "457172",
      "desired_state": {
        "brightness_updated_at": 1426548902.937418,
        "external_power": null,
        "firmware_version": "16974848",
        "update_needed_updated_at": null,
        "cost": null,
        "units_updated_at": null,
        "identify_mode_updated_at": null,
        "update_needed": null,
        "powered_updated_at": 1426548902.9374111,
        "budget_velocity_updated_at": null,
        "updating_firmware_updated_at": null,
        "powering_mode": "dumb",
        "units": null,
        "budget_percentage": null,
        "firmware_version_updated_at": 1426548902.9374249,
        "identify_mode": null,
        "battery": null,
        "battery_updated_at": null,
        "color": null,
        "consumption_updated_at": null,
        "consumption": null,
        "updating_firmware": null,
        "schedule_enabled": null,
        "color_updated_at": null,
        "last_error": null,
        "powered": true,
        "connection": true,
        "powering_mode_updated_at": null,
        "budget_percentage_updated_at": null,
        "external_power_updated_at": null,
        "budget_velocity": null,
        "last_error_updated_at": null,
        "connection_updated_at": 1426548902.937392,
        "schedule_enabled_updated_at": null,
        "cost_updated_at": null,
        "brightness": 0.04113207
      },
      "local_scene_id": null
    }
  ],
  "icon_id": 2,
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "97f894fd33e1db7bc97e75a4073d582be50dc9f1"
    }
  }
}

**Comment by EricMCSE76** [comment]
Sorry you were right I pasted in the wrong info....just updated it with one of the shortcuts that is failing.

**Comment by trunzoc** [comment]
release 1.1.0 updated with a new zip.  please give it a test and let me know

**Comment by EricMCSE76** [comment]
Confirmed to have fixed the shortcuts and groups are working.  Issue closed :) THANKS!!
