### ISSUE TITLE
TODO LIST:

### ISSUE THREAD

**Issue by trunzoc** [trunzoc/WinkAtHome#6]
-~~Manufacturer specific icons when possible (I will not be including thermostats in this)~~

-~~replace the Leviton receptacle icon with an actual icon of a receptacle.~~

-~~Display "update availalbe" if any device has a pending update~~

~~-SSH option~~ (SSL Implemented on public site. Local users will be responsible for getting their own cert)

**Comment by gorpus1959** [comment]
Greetings.. Any chance you will have this available for OSX ?

**Comment by trunzoc** [comment]
This seems to suggest it's possible, or will be soon...
http://weblogs.asp.net/scottgu/announcing-open-source-of-net-core-framework-net-core-distribution-for-linux-osx-and-free-visual-studio-community-edition

The work would be on your end though.  I wouldn't have to change anything here
