### ISSUE TITLE
FEATURE REQUEST - Drag & Drop sorting of controllable devices

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#7]
Drag and Drop would be a nice to have enhancement to arrange your devices. Alphabetical is fine but sometimes it is easy to group like devices that are not named similarly and that do not live in groups.
If drag and drop is too much effort for little reward, some sort ordering by assigning numeric value to a device would also work.

**Comment by trunzoc** [comment]
I spent all day playing with drag&drop.  not a fan of current implementation and I didn't want to burn more time on it today.  I did make some progress, but I think i need to overhaul the way the page is designed to make it work.

In the meantime, I did add arrangement of a sort. 
Click the info button on the controllable devices screen. at the bottom is a position textbox.  enter the number of where you want the device to be and click set.

please test pre-release v1.5.5585.33214
https://github.com/trunzoc/WinkAtHome/releases/tag/v1.5.5585.33214

**Comment by ghost** [comment]
Cool!

I just got and installed a Rachio Iro.

I will send you JSON once I have it going.

Sent from my iPhone

On Apr 17, 2015, at 7:44 PM, trunzoc notifications@github.com wrote:

I spent all day playing with drag&drop. not a fan of current implementation
and I didn't want to burn more time on it today. I did make some progress,
but I think i need to overhaul the way the page is designed to make it work.

In the meantime, I did add arrangement of a sort.
Click the info button on the controllable devices screen. at the bottom is
a position textbox. enter the number of where you want the device to be and
click set.

please test pre-release v1.5.5585.33214
https://github.com/trunzoc/WinkAtHome/releases/tag/v1.5.5585.33214
