### ISSUE TITLE
FEATURE REQUEST - Auto update to new releases

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#8]
Probably a long way off, but for the average folk downloading unzipping and replacing files regularly is a pain. ;-)

**Comment by trunzoc** [comment]
Ya.  I have a setup project attached on my end, that dumps to an exe.  I haven’t been happy with the output.  I WANT it to handle all the IIS configuration and such but it can’t

**Comment by trunzoc** [comment]
Version 2.0

https://github.com/trunzoc/WinkAtHome/releases/tag/v2.0.5603.18144

update to this, then never unzip again.
