### ISSUE TITLE
Binary Switch on Wink Relay which is configured to control a Shortcut 

### ISSUE THREAD

**Issue by davidgruhin** [trunzoc/WinkAtHome#9]
Binary Switch on Wink Relay which is configured to control a Shortcut  should probably not show up in controllable device.

My relay has 1 switch wired to an actual Light load. The second switch is not wired to anything and setup to fire a Shortcut.

In Wink@Home the switch setup to control a shortcut shows up as "Switch" and can be clicked.  This seems duplicative and contrary to the functionality in the main Wink app.  

The switch if not configured to a wired load should be hidden.

Here is the output from the switch configured to a shortcut:

{
  "binary_switch_id": "30320",
  "name": "Switch",
  "locale": "en_us",
  "units": {},
  "created_at": 1422813943,
  "hidden_at": null,
  "capabilities": {},
  "subscription": {
    "pubnub": {
      "subscribe_key": "sub-c-f7bf7f7e-0542-11e3-a5e8-02ee2ddab7fe",
      "channel": "8afe2bdfa540e4459b510bff44db636388afea88|binary_switch-30320|user-186645"
    }
  },
  "user_ids": [
    "186645"
  ],
  "triggers": [],
  "desired_state": {
    "powered": false,
    "powering_mode": "none"
  },
  "manufacturer_device_model": null,
  "manufacturer_device_id": null,
  "device_manufacturer": null,
  "model_name": null,
  "upc_id": null,
  "gang_id": "2997",
  "hub_id": "98045",
  "local_id": "2",
  "radio_type": "project_one",
  "last_reading": {
    "connection": true,
    "connection_updated_at": 1429016828.833034,
    "powered": false,
    "powered_updated_at": 1429016828.8330438,
    "powering_mode": "none",
    "powering_mode_updated_at": 1422824216.9928842,
    "consumption": null,
    "consumption_updated_at": null,
    "cost": null,
    "cost_updated_at": null,
    "budget_percentage": null,
    "budget_percentage_updated_at": null,
    "budget_velocity": null,
    "budget_velocity_updated_at": null,
    "summation_delivered": null,
    "summation_delivered_updated_at": null,
    "sum_delivered_multiplier": null,
    "sum_delivered_multiplier_updated_at": null,
    "sum_delivered_divisor": null,
    "sum_delivered_divisor_updated_at": null,
    "sum_delivered_formatting": null,
    "sum_delivered_formatting_updated_at": null,
    "sum_unit_of_measure": null,
    "sum_unit_of_measure_updated_at": null,
    "desired_powered": false,
    "desired_powered_updated_at": 1422824138.418901,
    "desired_powering_mode": "none",
    "desired_powering_mode_updated_at": 1422824216.9928727
  },
  "current_budget": null,
  "lat_lng": [
    0.0,
    0.0
  ],
  "location": "",
  "order": 0
}

**Comment by ghost** [comment]
Powering Mode - None = switch configured to anything but a real wired light

Powering Mode - Dumb = Wired load attached to the button

**Comment by trunzoc** [comment]
Got it.  Will make the changes this evening.

Thank you!

**Comment by EricMCSE76** [comment]
Interesting... I'll have to go through my configuration on Relay again.  I don't recall seeing that difference when we were experimenting with it the other day.  I tried a few different combinations of smart, binary, nothing at all.  

I guess I'd argue that if a graphical representation of the relay with "clickable" buttons is going to be displayed - they should show up in controllable devices.  In the main wink app - both buttons are actionable if a shortcut is assigned to a button.
![img_5269](https://cloud.githubusercontent.com/assets/11870446/7169643/6c904054-e395-11e4-905f-aeb4d89748a5.JPG)

From above -------------------------------------------------------------------
In Wink@Home the switch setup to control a shortcut shows up as "Switch" and can be clicked. This seems duplicative and contrary to the functionality in the main Wink app.

**Comment by ghost** [comment]
While I can agree that it does work to push the "virtual" button in the Wink App for the relay as shown above to get the shortcut action, from a UI perspective I would say that on this web dashboard it is just clutter to show the SHORTCUTS and a Button that would trigger the same action.

Just my 2 cents

**Comment by trunzoc** [comment]
I have to agree with David on this one.  The duplicate functioning item isn't gone from the webpage, it's just stashed as it would take up real estate on the already congested "overview" pages.
